### ISSUE TITLE
Coverage for Microsoft PKI policy requirements

### ISSUE THREAD

**Issue by sleevi** [zmap/zlint#363]
This is a top-level issue to capture overall progress towards having acceptable ZLint coverage for the [Microsoft PKI policy requirements](https://aka.ms/rootcert). It replaces the more general discussion from #277.

The list below should be considered **incomplete** until someone has time to do a full read through of the PKI Policy comparing the requirements listed with the existing ZLint lints. Any requirements not addressed (or that could be addressed with stricter lint results) should have corresponding issues created. Once the issue is created leave a comment on this overall issue to have the list updated.

I've started this issued based on my preparing a [CA/Browser Forum Browser Alignment branch](https://github.com/cabforum/documents/compare/master...sleevi:2019-10-Browser_Alignment) for the BRs.

## Required data/tooling
* [ ] SPKI data for trusted roots - https://github.com/zmap/zlint/issues/359

## Required lints (**INCOMPLETE**):
* [ ] [Section 4: Program Technical Requirements](https://docs.microsoft.com/en-us/security/trusted-root/program-requirements#4-program-technical-requirements)
  * [ ] Separate EKUs on intermediates - https://github.com/zmap/zlint/issues/360
  * [ ] Require the CABF EKUs on end-entity certificates - https://github.com/zmap/zlint/issues/361
  * [ ] OCSP URLs MUST be present in end-entity certificates - https://github.com/zmap/zlint/issues/362
